package com.example.JustEat.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Base class for all JPA entities in the application.
 * Provides common fields: auto-generated ID and automatic creation/update timestamps.
 * Uses @MappedSuperclass so fields are inherited by subclasses without creating a separate table.
 */
@MappedSuperclass
@Getter
@Setter
public abstract class BaseEntity {
    // Primary key - auto-generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Automatically set when entity is first persisted
    @CreationTimestamp
    private LocalDateTime createdAt;

    // Automatically updated whenever entity is modified
    @UpdateTimestamp
    private LocalDateTime updatedAt;

}
