name: JustEat CI/CD

on:
  push:
    branches:
      - master

jobs:

  backend:
    name: Backend Build & Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: JustEat/Backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Backend
        run: mvn clean package -DskipTests

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Docker Image
        run: |
          docker build -t geetanjali09/backendfoodapp:latest .

      - name: Push Backend Docker Image
        run: |
          docker push geetanjali09/backendfoodapp:latest

      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull geetanjali09/backendfoodapp:latest

            docker stop backend || true
            docker rm backend || true

            docker run -d \
              --name backend \
              -p 8090:8090 \
              geetanjali09/backendfoodapp:latest

  frontend:
    name: Frontend Build & Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: JustEat/Frontend/JustEat_frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Frontend Docker Image
        run: |
          docker build -t geetanjali09/frontendfoodapp:latest .

      - name: Push Frontend Docker Image
        run: |
          docker push geetanjali09/frontendfoodapp:latest

      - name: Deploy Frontend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull geetanjali09/frontendfoodapp:latest

            docker stop frontend || true
            docker rm frontend || true

            docker run -d \
              --name frontend \
              -p 5173:5173 \
              geetanjali09/frontendfoodapp:latest
